---
# For authentication are used environment variables AWS_ACCESS_KEY, AWS_SECRET_KEY, EC2_URL, AWS_REGION, AWS_SECURITY_TOKEN

- name: Create server Amazon
  hosts: all
  tasks:
    - name: Gather ec2 instance types info
      ec2_vpc_net_facts:
      register: networks

    - name: Gather info
      ec2_eni_facts:
      register: interfaces

#    - name: Gather info
#      ec2_ami_facts:
#      register: images

    - name: Gather info
      ec2_vpc_subnet_facts:
      register: subnets

    - name: Gather info
      ec2_instance_type_facts:


    - name: Create infrastructure using TOSCA template
      cloud_infra_create:
        template: tosca-server-example.yaml
        debug: true
        cloud_provider: amazon
        facts: "{{ ansible_facts }}"
        # To pass info you can use either facts field
        # either pass facts separately, choosing which you need and which not
        ec2_eni_facts: "{{ interfaces }}"
#        ec2_ami_facts: "{{ images }}"
        ec2_vpc_facts: "{{ networks }}"
        ec2_subnet_facts: "{{ subnets }}"
      register: infra_result
