- name: Create server Openstack
  hosts: localhost
  tasks:
    # Gather info if your tosca template uses node_filter attributes
    - name: Gather flavor info
      os_flavor_info:
        cloud: ispras
      register: flavors

    - name: Gather image info
      os_image_info:
        cloud: ispras
      register: images

    - name: Gather network info
      os_networks_info:
        cloud: ispras
      register: networks

    - name: Gather port info
      os_port_info:
        cloud: ispras
      register: ports

    - name: Gather server info
      os_server_info:
        cloud: ispras
      register: servers

    - name: Gather subnets info
      os_subnets_info:
        cloud: ispras
      register: subnets

    - name: save all facts
      set_fact:
        openstack_facts: 
          openstack_flavor_facts: "{{ ansible_facts.openstack_flavors }}"
          openstack_image_facts: "{{ ansible_facts.openstack_images }}"
          openstack_network_facts: "{{ ansible_facts.openstack_networks }}"
          openstack_port_facts: "{{ ansible_facts.openstack_ports }}"
          openstack_server_facts: "{{ ansible_facts.openstack_servers }}"
          openstack_subnet_facts: "{{ ansible_facts.openstack_subnets }}"

    - name: Write cloud facts in file
      copy:
        content: "{{ openstack_facts }}"
        dest: /home/valerius/Downloads/openstack_facts.json
      