---

- hosts: all
  name: Create openstack cluster
  tasks:
    - name: Create SecurityGroup
      os_security_group:
        cloud: ispras
        name: server_kube_master_security_group
    - name: Create Port
      os_port:
        cloud: ispras
        network: test-two-routers
        fixed_ips:
        - ip_address: 192.168.12.26
        name: server_kube_master_port_0
        vnic_type: normal
    - name: Create SecurityGroupRule
      os_security_group_rule:
        cloud: ispras
        direction: ingress
        port_range_max: 1000
        port_range_min: 1000
        protocol: tcp
        remote_ip_prefix: 0.0.0.0
        security_group: server_kube_master_security_group
    - name: Create Server
      os_server:
        cloud: ispras
        availability_zone: nova
        config_drive: false
        flavor: ispras.medium
        image: Ubuntu 16.04 Xenial Trusty x86_64 cloud image (recovered)
        meta: "kube_master=true"
        name: server-kube-master
        network: test-two-routers
#        nics:
#          - server_kube_master_port_0
        security_groups:
          - server_kube_master_security_group
